---

jobs:
  - name: datascience
    plan:
      - get: git-repo
        trigger: true
      - task: build-image
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: jupyter/repo2docker
              tag: 8a5b1ef
          inputs:
            - name: git-repo
          run:
            path: ./git-repo/ci/scripts/build-image.sh

resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/natbusa/dsp-titanic.git
      branch: master
