---

jobs:
  - name: datascience
    plan:
      - get: repo
        trigger: true
      - task: build-image
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: jupyter/repo2docker
              tag: 8a5b1ef
          inputs:
            - name: git-repo
          run:
            path: ci/scripts/build-image.sh
            dir: repo
          outputs:
            - name: build
      - put: repo-docker-image
        params:
          build: repo

resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/natbusa/dsp-titanic.git
      branch: master
  - name: repo-docker-image
    type: docker-image
    source:
      email: natalino.busa@gmail.com
      repository: http://registry-docker-registry.dsw.svc.cluster.local:5000/natbusa/test:onetwothree
      insecure_registries: http://registry-docker-registry.dsw.svc.cluster.local:5000
